# Generated by Django 4.2.6 on 2023-10-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0002_delete_entidad_delete_post_delete_tipo_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='TIPO_CHOICES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
