# Generated by Django 4.2.6 on 2023-10-20 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_post_delete_entidad_delete_tipo_choices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Crear Post'},
        ),
    ]
